higherkindness/skeuomorph

.travis.yml
build.sbt
project/plugins.sbt

Once `skeuomorph` has been moved from [frees-io](https://github.com/frees-io) to [higherkindness](https://github.com/higherkindness) organization, does it make sense to start using `sbt-org-policies` instead of `sbt-freestyle` plugin?
It closes #4, #5 and #6

Use sbt-org-policies plugin

---

build.sbt
src/test/scala/PrinterSpec.scala

Check that the `Printer` instance for `ContravariantMonoidal`, `Monoid`, and `Semigroup` are lawful

Add some more tests

---

build.sbt
project/plugins.sbt

otherwise it will try to pubish the artifact as "higherkindness" %% "skeuomorph"

change the organization to io.higherkindness

---

src/main/scala/higherkindness/skeuomorph/mu/print.scala

we can flatten the tuples because we don't use `>*<` anymore but just `(a, b, c).contramapN(whatever)`

make code more readable by using contramapN

---

src/main/scala/higherkindness/skeuomorph/mu/print.scala
src/main/scala/higherkindness/skeuomorph/mu/protocol.scala
src/main/scala/higherkindness/skeuomorph/protobuf/ParseProto.scala
src/main/scala/higherkindness/skeuomorph/protobuf/Protocol.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala
src/test/scala/higherkindness/skeuomorph/protobuf/author.proto
src/test/scala/higherkindness/skeuomorph/protobuf/book.proto

This PR closes #74 
In summary:
If we have `author.proto`:
```proto
package com.acme;
message Author {
string name = 1;
string nick = 2;
}
```
and a `book.proto`:
```proto
package com.acme;
import "author.proto";
message Book {
int64 isbn = 1;
string title = 2;
repeated Author author = 3;
}
```
If we try to produce the scala code given the `book.proto`
We are generating code like this:
```scala
package com.acme
object book {
@message final case class Author(name: String, nick: String)
@message final case class Book(isbn: Long, title: String, author: List[Author])
}
```
We are generating code like this:
```scala
package com.acme
import com.acme.author.Author
object book {
@message final case class Book(isbn: Long, title: String, author: List[Author])
}
```

Propagates imports instead of cloning dependent messages

---

version.sbt

- See https://github.com/higherkindness/skeuomorph/pull/92

Bump version to release optional fields work

---

src/main/scala/higherkindness/skeuomorph/mu/print.scala
src/main/scala/higherkindness/skeuomorph/mu/protocol.scala
src/main/scala/higherkindness/skeuomorph/protobuf/ParseProto.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala

CompressionType and useIdiomaticEndpoints for Protobuf and Avro

---

src/main/scala/higherkindness/skeuomorph/Printer.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/circe/package.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/print.scala
src/test/scala/higherkindness/skeuomorph/openapi/JsonSchemaPrintSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiPrintSpecification.scala

This PR contains the following features:
* Moves **encoder/decoder** to its own package
* Prints **encoder/decoder** to companion object.
* **Avoids** the creation of encoder/ decoder for **basic types**.
* Converts objects without properties to `io.circe.Json`
* Creates **reusable printers** (e.g. objectDef, caseClassWithCodecsDef)
* Prints **encoders/decoders** for anonymous objects.
* Prints **encoders/decoders** for **Enums**.
This is a continuation of the following previous PRs:
- https://github.com/higherkindness/skeuomorph/pull/102
- https://github.com/higherkindness/skeuomorph/pull/97
- https://github.com/higherkindness/skeuomorph/pull/90
- https://github.com/higherkindness/skeuomorph/pull/81
You can find, the objectives for all these PRs here: …

Print encoders

---

src/main/scala/higherkindness/skeuomorph/mu/Optimize.scala
src/main/scala/higherkindness/skeuomorph/mu/print.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala

This PR fixes #113 
It converts the `TOption` values within `TCoproduct` into `TRequired`.

Removes the optionality in Coproducts

---

src/main/scala/higherkindness/skeuomorph/openapi/JsonDecoders.scala
src/main/scala/higherkindness/skeuomorph/openapi/Optimize.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/circe/package.scala
src/main/scala/higherkindness/skeuomorph/openapi/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/schema.scala
src/test/scala/higherkindness/skeuomorph/openapi/NestedObjectSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiNestedObjectSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiPrintSpecification.scala

You can find, the objectives for all these PRs here: https://github.com/47deg/marlow/issues/188
> Generating http4s client code based on a Open API specification using http4s v0.20 and 0.18 using circe to encode/decode.
**Open api spec** is based on **Yaml/Json** to define types, this means that not all the types have a name. You can inline objects if you want to. However, this can create a problematic situation when the objects are nested inside the *Yaml/Json* tree. Let's look at an example when `Person` is inline inside a `Owner`. 
```yaml
Owner:
required:
- person
properties:
address: 
type: string
person:
type: object
required:
- name
- surname
properties:
name:
type: string
surname:
type: string
age: 
type: integer
```
However, when we generate code, we can create the following …

Nested object

---

src/main/scala/higherkindness/skeuomorph/openapi/JsonDecoders.scala
src/main/scala/higherkindness/skeuomorph/openapi/JsonEncoders.scala
src/main/scala/higherkindness/skeuomorph/openapi/JsonSchema.scala
src/main/scala/higherkindness/skeuomorph/openapi/Optimize.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/circe/package.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/schema.scala
src/test/scala/higherkindness/skeuomorph/instances.scala
src/test/scala/higherkindness/skeuomorph/openapi/JsonSchemaDecoderSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/JsonSchemaPrintSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiDecoderSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiNestedObjectSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiPrintSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OperationIdSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/helpers.scala

You can find, the objectives for all these PRs here: https://github.com/47deg/marlow/issues/188
> Generating http4s client code based on a Open API specification using http4s v0.20 and 0.18 using circe to encode/decode.
**Open api spec** is based on _http_ and is not in a specific programming language. Names of different type of elements (e.g.: schema names, property names, reference names, etc.) can contain symbols, numbers, etc. or grammar rules that are not allowed in the target programming language (in this case _scala_) when we are generating code.  This could be problematic because we are generating code that it is not able to compile.
```yaml
components:
schemas:
general-error:
type: object
properties:
code:
type: integer
format: int32
message:
type: string
category:
type: object …
```

Normalize and more support for open api spec

---

build.sbt
src/main/scala/higherkindness/skeuomorph/openapi/JsonDecoders.scala
src/main/scala/higherkindness/skeuomorph/openapi/ParseOpenApi.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/print.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiDecoderSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiPrintSpecification.scala

You can find, the objectives for all these PRs here: https://github.com/47deg/marlow/issues/188
> Generating http4s client code based on a Open API specification using http4s v0.20 and 0.18 using circe to encode/decode.
It will require to create the `Parser` instances for _yaml_ and _json_. This will simplify the use the library and it will be required for *mu* project. We can create an instance for _json_ as following:
```scala
Parser[F, JsonSource, OpenApi[JsonSchemaF.Fixed]]
```
There are some situation we should not print anything. 
- We should print empty string for *models* when the *components / schemas* they don't provide any schemas.
- We should print empty string for *interface / implementation* when there are not paths defined.
- …

Open api parser

---

version.sbt

It seems the previous version release failed to deploy the artifacts to Sonatype:
```bash
java.io.IOException: PUT operation to URL https://oss.sonatype.org/service/local/staging/deploy/maven2/io/higherkindness/skeuomorph_2.11/0.0.12/skeuomorph_2.11-0.0.12-sources.jar failed with status code 504: Gateway Time-out
```
👉 https://travis-ci.org/higherkindness/skeuomorph/jobs/583544171#L1569

Release 0.0.13

---

build.sbt
src/main/scala/higherkindness/skeuomorph/Printer.scala
src/main/scala/higherkindness/skeuomorph/mu/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/circe/package.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/print.scala
src/test/scala/higherkindness/skeuomorph/openapi/JsonSchemaPrintSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiPrintSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OperationIdSpecification.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala
src/test/scala/higherkindness/skeuomorph/protobuf/models/hyphenated-name.proto
src/test/scala/higherkindness/skeuomorph/protobuf/service/book.proto

Fixes #114 
Added a new `identifier` combinator to `Printer`, which turns arbitrary strings into valid Scala identifiers by wrapping them with backticks if necessary. Unfortunately it wasn't possible to actually use the combinator in that many places; I ended up directly calling the underlying `Printer.toValidIdentifier` instead.
I didn't want to write my own buggy implementation of the Scala lexical spec, so I used scalameta to take care of the logic to decide when something needs to be backticked.
The printing of Mu schemas/protocols was pretty trivial to fix. The OpenAPI printing, on the other hand, is much more complex. There is a lot more code being generated, and there was already a lot of string manipulation/normalization going on. Because of this, I'm not that confident I've …

Avoid generating invalid Scala identifiers when printing schemas and protocols

---

src/main/scala/higherkindness/skeuomorph/avro/Protocol.scala
src/main/scala/higherkindness/skeuomorph/mu/Transform.scala
src/main/scala/higherkindness/skeuomorph/mu/print.scala
src/main/scala/higherkindness/skeuomorph/mu/schema.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala
src/test/scala/higherkindness/skeuomorph/protobuf/service/book.proto

See https://github.com/47deg/pbdirect/pull/20
Because it is still a plain old sealed abstract class + case object hierarchy, this change will not affect Avro serialization using avro4s (confirmed with manual testing).
Note: This change assumes that enumeratum is on Mu's classpath, which is not yet true. [PR to add it as a dependency](https://github.com/higherkindness/mu/pull/719).
Update: I've tested the whole `.proto` -> src gen -> gRPC server flow manually using locally-published artifacts and confirmed that protobuf enumerations now work 🎉

Use enumeratum IntEnum for generated enums

---

.travis.yml
src/main/scala/higherkindness/skeuomorph/mu/Transform.scala
src/main/scala/higherkindness/skeuomorph/mu/print.scala
src/main/scala/higherkindness/skeuomorph/mu/schema.scala
src/main/scala/higherkindness/skeuomorph/protobuf/ParseProto.scala
src/main/scala/higherkindness/skeuomorph/protobuf/schema.scala
src/test/scala/higherkindness/skeuomorph/instances.scala
src/test/scala/higherkindness/skeuomorph/mu/comparison/ComparisonSpec.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala

See https://github.com/47deg/pbdirect/pull/21
If a Mu user chooses Protobuf for the serialization of messages, the pbdirect library will make use of these annotations to discover the correct index number of each field.
In the case of Avro serialization, the annotation will simply be ignored by avro4s.
Also tidied up the generated code slightly by putting each field on a separate line.

Add pbIndex annotation to generated Scala code

---

src/main/scala/higherkindness/skeuomorph/mu/print.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala

Previously we were generating a made-up type `Cop[A :: B :: TNil]`. There is [code in the Mu sbt plugin](https://github.com/higherkindness/mu-scala/blob/0dab66791fef6caf7123df613213ba351475049a/modules/idlgen/core/src/main/scala/higherkindness/mu/rpc/idlgen/proto/ProtoSrcGenerator.scala#L65-L71) to rewrite it to `A :+: B :+: CNil` using some regex nastiness. We may as well generate a real type in the first place and remove the need for rewriting.

Generate a shapeless Coproduct instead of a placeholder type

---

src/main/scala/higherkindness/skeuomorph/mu/print.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala

* `scala.Map` should be `scala.Predef.Map`
* Can't write shapeless coproduct types using infix notation.
The compiler isn't happy with using a qualified type (e.g. `_root_.shapeless.:+:`) in infix position.
Updated to write the type as e.g. `_root_.shapeless.:+:[Int, _root_.shapeless.:+:[String, _root_.shapeless.CNil]]`. It's not pretty, but it compiles.

Fix a couple of compilation issues in the generated code

---

build.sbt
docs/docs/docs/index.md
src/main/scala/higherkindness/skeuomorph/mu/codegen.scala
src/main/scala/higherkindness/skeuomorph/mu/print.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala
src/test/scala/higherkindness/skeuomorph/protobuf/service/book.proto

I find this easier to work with than the existing printer, which is basically doing fancy string concatenation, because scalameta gives us a nice AST with which to model the code. It also provides quasiquotes, which are very convenient, and it indents the code correctly for us.
(Unfortunately we end up losing a lot of the type information when we do a catamorphism, and we have to add it back in using casting. I haven't found a nice way around this. Open to suggestions.)
The codegen takes a stream type constructor as an argument, allowing the sbt plugin to choose between FS2 and Monix for streaming more cleanly than it does currently. It also includes an `import higherkindess.mu.rpc.protocol._` statement so we don't have to add the import in the sbt plugin.
If people are happy with the …

Use scalameta for codegen

---

docs/docs/docs/optimizations.md
src/main/scala/higherkindness/skeuomorph/avro/Protocol.scala
src/main/scala/higherkindness/skeuomorph/mu/Optimize.scala
src/main/scala/higherkindness/skeuomorph/mu/Transform.scala
src/main/scala/higherkindness/skeuomorph/mu/codegen.scala
src/main/scala/higherkindness/skeuomorph/mu/comparison/Comparison.scala
src/main/scala/higherkindness/skeuomorph/mu/comparison/Path.scala
src/main/scala/higherkindness/skeuomorph/mu/print.scala
src/main/scala/higherkindness/skeuomorph/mu/schema.scala
src/main/scala/higherkindness/skeuomorph/protobuf/ParseProto.scala
src/main/scala/higherkindness/skeuomorph/protobuf/print.scala
src/main/scala/higherkindness/skeuomorph/protobuf/schema.scala
src/test/scala/higherkindness/skeuomorph/instances.scala
src/test/scala/higherkindness/skeuomorph/mu/comparison/ComparisonSpec.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala
src/test/scala/higherkindness/skeuomorph/protobuf/models/opencensus/resource.proto
src/test/scala/higherkindness/skeuomorph/protobuf/models/opencensus/trace.proto
src/test/scala/higherkindness/skeuomorph/protobuf/service/book.proto

In `.proto` files it is possible (and quite common) to nest messages and enums inside other messages, and reference them for field types in other message, e.g.
```protobuf
message Person {
message Name {
string given_name = 1;
string family_name = 2;
}
Name name = 1;
int32 date_of_birth = 2;
}
message User {  
enum Type {
NORMAL = 0;
ADMIN = 1;
}
int32 id = 1;
Person.Name name = 2;
Type type = 3;  
} 
```
This PR adds support for these nested types.
Sorry the diff is pretty huge, but the major changes are:
1. Correctly build the fully-qualified names for nested types when parsing a `.proto` file. (We were generating nonsense names because the logic wasn't written with nested types in mind.)
2. Make sure to collect all messages and enums when parsing a `.proto` file, no matter how deeply …

Support protobuf nested messages and enums

---

src/main/scala/higherkindness/skeuomorph/FileUtils.scala
src/main/scala/higherkindness/skeuomorph/avro/Protocol.scala
src/main/scala/higherkindness/skeuomorph/avro/schema.scala
src/main/scala/higherkindness/skeuomorph/mu/codegen.scala
src/main/scala/higherkindness/skeuomorph/mu/comparison/Comparison.scala
src/main/scala/higherkindness/skeuomorph/mu/protocol.scala
src/main/scala/higherkindness/skeuomorph/openapi/JsonDecoders.scala
src/main/scala/higherkindness/skeuomorph/openapi/JsonEncoders.scala
src/main/scala/higherkindness/skeuomorph/openapi/ParseOpenApi.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/circe/package.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/print.scala
src/main/scala/higherkindness/skeuomorph/openapi/schema.scala
src/main/scala/higherkindness/skeuomorph/protobuf/ParseProto.scala
src/main/scala/higherkindness/skeuomorph/protobuf/schema.scala
src/test/scala/higherkindness/skeuomorph/PrinterSpec.scala
src/test/scala/higherkindness/skeuomorph/avro/AvroSpec.scala
src/test/scala/higherkindness/skeuomorph/instances.scala
src/test/scala/higherkindness/skeuomorph/mu/comparison/ComparisonSpec.scala
src/test/scala/higherkindness/skeuomorph/openapi/JsonSchemaDecoderSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/JsonSchemaPrintSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/NestedObjectSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiDecoderSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiNestedObjectSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiPrintSpecification.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiSchemaSpec.scala
src/test/scala/higherkindness/skeuomorph/openapi/helpers.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala

This annotation was only used for IDL generation, which we don't do anymore.
(also accidentally apply the formatter)

Remove `@message` annotation from generated case classes

---

version.sbt

This is so we can remove the `@message` annotation from mu-scala, as it's a relic of the IDL generation feature.

Release 0.0.21

---

version.sbt

This PR releases a new skeuomorph version cross-compiled to Scala 2.12.x and 2.13.x.

Releases 0.0.22

---

project/plugins.sbt
src/main/scala/higherkindness/skeuomorph/mu/codegen.scala
src/test/scala/higherkindness/skeuomorph/avro/AvroSpec.scala

This annotation is deprecated and will be deleted.

Don't add `@option` when generating Mu code

---

src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/circe/package.scala
src/main/scala/higherkindness/skeuomorph/openapi/client/http4s/print.scala
src/test/scala/higherkindness/skeuomorph/openapi/OpenApiPrintSpecification.scala

This is needed since we need some implicit instances (like `Show[A]`) and not only syntax.

Restores the cats implicits import

---

src/main/scala/higherkindness/skeuomorph/protobuf/ParseProto.scala
src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala

Adds support in `protoc-gen` to pass the version to the protoc-gen.

fixed 'No support for M1 Macs' #559
