higherkindness/skeuomorph

version.sbt
=> release 0.0.1 version

docs/src/main/tut/optimizations.md
Small pull request that fixes a typo in the optimizations documentation.
=> fix typo in optimizations documentation

.gitignore, build.sbt
Just adding new files/folders that `git` should ignore. I have also run `scalafmt` to format the code
=> Adds new entries in gitignore file

build.sbt
=> Update cats to 1.5.0

README.md, docs/src/main/tut/optimizations.md, readme/README.md, src/main/scala/Printer.scala, src/main/scala/avro/Protocol.scala, src/main/scala/avro/schema.scala, src/main/scala/catz/contrib/ContravariantMonoidalSyntax.scala, src/main/scala/catz/contrib/Decidable.scala, src/main/scala/mu/Optimize.scala, src/main/scala/mu/Transform.scala, src/main/scala/mu/print.scala, src/main/scala/mu/protocol.scala, src/main/scala/mu/schema.scala, src/main/scala/openapi/JsonEncoders.scala, src/main/scala/openapi/JsonSchema.scala, src/main/scala/openapi/schema.scala, src/main/scala/protobuf/print.scala, src/main/scala/protobuf/schema.scala, src/test/scala/PrinterSpec.scala, src/test/scala/avro/AvroSpec.scala, src/test/scala/instances.scala, src/test/scala/mu/OptimizeSpec.scala
Make `higherkindness` the root package for the project.
Close #18
=> Move under higherkindness package

.travis.yml, build.sbt, version.sbt
This project fixes the release process (committing files should work now) and readme files should be updated correctly.
Fixes https://github.com/higherkindness/skeuomorph/issues/51
=> Build Fixes and Release 0.0.3

src/main/scala/higherkindness/skeuomorph/avro/Protocol.scala, src/main/scala/higherkindness/skeuomorph/avro/package.scala, src/main/scala/higherkindness/skeuomorph/avro/schema.scala, src/main/scala/higherkindness/skeuomorph/mu/Transform.scala, src/main/scala/higherkindness/skeuomorph/mu/protocol.scala, src/main/scala/higherkindness/skeuomorph/uast/types.scala
Now Avro schema is written in terms of UAST.
=> [UAST] - Avro

build.sbt, src/main/scala/higherkindness/skeuomorph/protobuf/ParseProto.scala, version.sbt
This PR prevents to package scoverage information as part of the artifact.
Decompiled class:
=> Fixes scoverage transitive issues

src/main/scala/higherkindness/skeuomorph/mu/print.scala
This reverts commit 68b942b4a1b8404db4839fdcf5a290d9e6f0c1c7.
Made against master by mistake, sorry
=> Revert "Use the fully qualified name for fs2 Stream"

src/main/scala/higherkindness/skeuomorph/mu/print.scala, src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala
This avoids adding the import.
=> Append the `fs2` prefix to the `Stream`

src/main/scala/higherkindness/skeuomorph/mu/comparison/Comparison.scala
This should fix the broken deployment.
=> Fix scaladoc generation

src/main/scala/higherkindness/skeuomorph/mu/print.scala, src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala, version.sbt
This was causing some headaches downstream in Mu, better to revisit this in its own release I think.
=> Remove fs2 prefix

src/main/scala/higherkindness/skeuomorph/mu/print.scala, src/main/scala/higherkindness/skeuomorph/mu/protocol.scala, src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala
issue https://github.com/higherkindness/skeuomorph/issues/86
=> Support for compression

src/main/scala/higherkindness/skeuomorph/mu/print.scala, src/main/scala/higherkindness/skeuomorph/mu/protocol.scala, src/main/scala/higherkindness/skeuomorph/protobuf/ParseProto.scala, src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala
Analogous to #101 but against `uast` branch.
=> UAST: CompressionType and useIdiomaticEndpoints for Protobuf and Avro

version.sbt
.. including all the scala upgrades by @scala-steward and publishing the new brand and microsite.
=> Releases 0.0.16

.travis.yml, README.md, build.sbt, docs/docs/docs/index.md
* Update Travis requisites for sbt-microsites 1.0
* Use https links where appropriate
=> Travis microsite stage requisites update

docs/docs/docs/index.md
Make the Avro and Protobuf more consistent with each other for easy comparison.
=> Rewrite the doc examples slightly for consistency

build.sbt
Now, with this change, [this section](https://github.com/higherkindness/skeuomorph/blob/2b02702/docs/docs/docs/index.md#installation) should be auto-updated with every release.
=> Includes docs subfolders

.travis.yml, docs/docs/docs/optimizations.md
* Fix compile error in docs
* Fix Travis config to actually check the docs compile (this broke when we switched from tut to mdoc)
=> Fix broken docs

src/main/scala/higherkindness/skeuomorph/mu/codegen.scala, src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala
See https://github.com/higherkindness/mu-scala/pull/871
=> Wrap streaming responses in effect type

.scalafmt.conf, src/main/scala/higherkindness/skeuomorph/Printer.scala, src/main/scala/higherkindness/skeuomorph/avro/schema.scala, src/main/scala/higherkindness/skeuomorph/mu/comparison/Comparison.scala, src/main/scala/higherkindness/skeuomorph/protobuf/schema.scala
=> Update scalafmt-core to 2.6.0

build.sbt, src/main/scala/higherkindness/skeuomorph/mu/codegen.scala, src/test/scala/higherkindness/skeuomorph/protobuf/ProtobufProtocolSpec.scala, src/test/scala/higherkindness/skeuomorph/protobuf/models/type/date.proto
Fixes https://github.com/higherkindness/skeuomorph/issues/288
=> Escaping 'type' keyword in package (directory) names

.scalafmt.conf, src/main/scala/higherkindness/skeuomorph/Printer.scala, src/main/scala/higherkindness/skeuomorph/mu/comparison/Comparison.scala
=> Update scalafmt-core to 2.6.1
